import { mkdirSync, writeFileSync } from 'node:fs';
import { compileSemanticConstruction } from '../src/geometryCompiler.ts';

// Node 24+ strips TypeScript types. This fixture exercises the real main compiler.
const construction = { objects: [
  { type: 'point', name: 'A', x: 1, y: 3 },
  { type: 'point', name: 'B', x: 0, y: 0 },
  { type: 'point', name: 'C', x: 5, y: 0 },
  { type: 'polygon', name: 'ABC', points: ['A', 'B', 'C'] },
  { type: 'altitudeFoot', name: 'D', from: 'A', to: ['B', 'C'] },
  { type: 'orthocenter', name: 'H', triangle: ['A', 'B', 'C'] },
] };
const commands = compileSemanticConstruction(construction);
const markdown = `# Deterministic construction fixture\n\nGenerated by \`node scripts/construction-proof.mjs\` (Node 24+), using the current main compiler. No AI provider is called.\n\n## Semantic input\n\n\`\`\`json\n${JSON.stringify(construction, null, 2)}\n\`\`\`\n\n## Actual compiler output\n\n\`\`\`text\n${commands.join('\n')}\n\`\`\`\n\nTo view it in GeoGebra, serve this repository locally and open \`docs/construction-demo.html\`. The applet requires network access to GeoGebra. The fixture is not evidence of live natural-language generation.\n`;
mkdirSync(new URL('../docs/', import.meta.url), {recursive:true});
writeFileSync(new URL('../docs/CONSTRUCTION.md', import.meta.url), markdown);
writeFileSync(new URL('../docs/construction-demo.html', import.meta.url), `<!doctype html>
<html lang="en"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>GeoGebra Copilot — compiler fixture</title>
<style>body{margin:24px;font:16px system-ui;color:#172b3a;background:#f7fafc}h1{font-size:25px;margin-bottom:6px}p{max-width:880px}#status{font-family:monospace}#applet{margin-top:18px}</style>
<h1>Triangle, altitude foot and orthocenter</h1>
<p>Actual output of GeoGebra Copilot's deterministic compiler. Fixed semantic input; no AI request.</p>
<div id="status">Loading GeoGebra…</div><div id="applet"></div>
<script src="https://www.geogebra.org/apps/deployggb.js"></script>
<script>
const commands = ${JSON.stringify(commands)};
const applet = new GGBApplet({appName:'classic',width:900,height:550,showToolBar:false,showAlgebraInput:false,showMenuBar:false,appletOnLoad(api){
  const failures=commands.filter(command => !api.evalCommand(command));
  api.setCoordSystem(-2,7,-1.5,4.5);
  const ok=failures.length===0 && api.exists('D') && api.exists('H');
  document.getElementById('status').textContent=ok ? commands.length+' compiler commands executed; D and H exist.' : 'Failed commands: '+failures.join('; ');
}},true); applet.inject('applet');
</script></html>`);
console.log(commands.join('\n'));
